[package]
name = "rusty_rain"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1" #use this sparingly, only to initialize some data. Simulation must be deterministic
log = "0.4.27"
env_logger = "0.11.8"
